### ISSUE TITLE
Paying for subscription doesn't unlock Premium features

### ISSUE THREAD

**Issue by gazpwc** [SourceNotify/macOS-App#2]
Describe the bug
Nearly the same issue as described in issue #1 but this time with a subscription. 
I've done the "Go Premium for €6,99/year" premium option but the app doesn't recognize this.

To Reproduce

Attempt to add GitLab
Click on the Premium prompt
Click "Go Premium for €6,99/year"
Pay
Get a prompt saying thank you
Application forgets you paid, and continues to ask for money

Expected behavior
Paying money should get you premium.

Desktop (please complete the following information):
OS: Monterey

**Comment by Mteixeira88** [comment]
Hello, looking into the problem, will update you soon

**Comment by Mteixeira88** [comment]
The problem should be solved in the next version (1.3.3), sorry for this problem

If you don't want to wait for AppStore review you can try to download the app from [here](https://github.com/SourceNotify/macOS-App/files/7881300/SourceNotify_1.3.3-130005.zip)

**Comment by gazpwc** [comment]
Great, thanks! I will try that.

**Comment by gazpwc** [comment]
Works now! Thanks for your support. 👍

**Comment by Mteixeira88** [comment]
Great. thanks for the feedback. will close the issue
